
variables:
  NUGET_PATH: 'C:\Tools\Nuget\nuget.exe'
  MSBUILD_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\msbuild.exe'
  MSTEST_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\MSTest.exe'
  XUNIT_PATH: packages\xunit.runner.console.2.3.1\tools\net452
  UNITTEST_FOLDER: '.\RaceHorologyLibTest\bin\x86\Release'

stages:
  - build
  - test

build_job:
  stage: build
  only:
    - branches
  script:
    - '& "$env:NUGET_PATH" restore'
    - '& "$env:MSBUILD_PATH" /p:Configuration=Release /clp:ErrorsOnly'
  artifacts:
    expire_in: 2 days
    paths:
      - '$env:UNITTEST_FOLDER'

test_job:
  stage: test
  only:
    - branches
  script:
    - '& "$env:MSTEST_PATH" /testcontainer:"$env:UNITTEST_FOLDER\RaceHorologyLibTest.dll"'
  dependencies:
    - build_job
    