name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:  
      - main


jobs:
  build:
    runs-on: [windows-latest]
    outputs:
      tag: ${{ steps.version.outputs.tag }}
      branch: ${{ steps.version.outputs.branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/cache@v1
        id: cache
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
    
      - name: Install Nuget
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: ${{ env.NUGET_VERSION}}

      - name: NuGet to restore dependencies as well as project-specific tools that are specified in the project file
        #if: steps.cache.outputs.cache-hit != 'true'
        run: nuget restore

      - id: version
        #if: ${{ startsWith(github.ref, 'refs/heads/main') }}
        name: Update build version
        run: |
          git fetch --unshallow --tags
          $versionString = git describe --tags $(git rev-list --tags --max-count=1)
          Write-Host "Retrieved tag version: $versionString"         
          if (!$versionString) {
            Write-Host "Could not retrieve tag - using 1.0.0.0 as fallback"
            $versionString="1.0.0.0" 
          }

          $version = $versionString.Split('.')
          $majorVersion = $version[0]
          $minorVersion = $version[1]
          $patchVersion = $version[2]
          $lastBuildVersion = $version[3]

          $newBuildVersion = ([int]::Parse($lastBuildVersion) + 1)
          $newVersionString = "$majorVersion.$minorVersion.$patchVersion.$newBuildVersion"
          Write-Host "New version: $newVersionString"
          echo "::set-output name=tag::$newVersionString"

          $branch = $env:GITHUB_REF | Select-String -Pattern '(?<=refs\/heads\/).*' | ForEach-Object { $_.Matches[0].Value }
          echo "::set-output name=branch::$branch"

      - name: Build DotNET
        run: |
           cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe /p:Configuration=Debug /p:Platform=x86 $Env:GITHUB_WORKSPACE
           .\MSBuild.exe /p:Configuration=Release /p:Platform=x86 $Env:GITHUB_WORKSPACE

      - name: Upload Test Programm
        uses: actions/upload-artifact@v2
        with:
          name: unittest_RaceHorologyLibTest
          path: ${{ github.workspace }}\RaceHorologyLibTest\bin\x86
          retention-days: 2

      - name: Build Installer
        run: |
           cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe /p:Configuration=Release /p:Platform=x86 $Env:GITHUB_WORKSPACE\RaceHorologySetup

      - name: Upload Installer
        uses: actions/upload-artifact@v2
        with:
          name: installer_RaceHorology
          path: ${{ github.workspace }}\RaceHorologySetup\bin\Release\RaceHorologySetup.msi
          retention-days: 21



  run_test:
    needs: build
    runs-on: [windows-latest]
    steps:
      - name: Download Test Programm
        uses: actions/download-artifact@v2
        with:
          name: unittest_RaceHorologyLibTest
          path: ${{ github.workspace }}\RaceHorologyLibTest\bin\x86

      - name: Setup VSTest Path
        uses: darenm/Setup-VSTest@v1
      
      - name: VSTest_Debug
        run: vstest.console.exe /Platform:x86 $Env:GITHUB_WORKSPACE\RaceHorologyLibTest\bin\x86\Debug\RaceHorologyLibTest.dll /TestCaseFilter:"TestCategory!=HardwareDependent&TestCategory!=IntegrationDsvOnline" /logger:trx
      
      - name: VSTest_Release
        run: vstest.console.exe /Platform:x86 $Env:GITHUB_WORKSPACE\RaceHorologyLibTest\bin\x86\Release\RaceHorologyLibTest.dll /TestCaseFilter:"TestCategory!=HardwareDependent&TestCategory!=IntegrationDsvOnline" /logger:trx

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: unittest_RaceHorologyLibTest_Results
          path: ${{ github.workspace }}\TestResults\**\*.trx 

  run_test_dsv_online:
    needs: build
    runs-on: [windows-latest]
    steps:
      - name: Download Test Programm
        uses: actions/download-artifact@v2
        with:
          name: unittest_RaceHorologyLibTest
          path: ${{ github.workspace }}\RaceHorologyLibTest\bin\x86

      - name: Setup VSTest Path
        uses: darenm/Setup-VSTest@v1
      
      - name: VSTest_Debug
        run: vstest.console.exe /Platform:x86 $Env:GITHUB_WORKSPACE\RaceHorologyLibTest\bin\x86\Debug\RaceHorologyLibTest.dll /TestCaseFilter:"TestCategory=IntegrationDsvOnline" /logger:trx
      
      - name: VSTest_Release
        run: vstest.console.exe /Platform:x86 $Env:GITHUB_WORKSPACE\RaceHorologyLibTest\bin\x86\Release\RaceHorologyLibTest.dll /TestCaseFilter:"TestCategory=IntegrationDsvOnline" /logger:trx

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: unittest_RaceHorologyLibTest_Results_DsvOnline
          path: ${{ github.workspace }}\TestResults\**\*.trx 
